export const animationEffects = {
  entrance: [
    { id: "appear", name: "Appear", category: "entrance", icon: "✨", defaultDuration: 0.0, supportedEffectOptions: [] },
    { id: "fade", name: "Fade", category: "entrance", icon: "🌫️", defaultDuration: 0.5, supportedEffectOptions: [] },
    { id: "fly-in", name: "Fly In", category: "entrance", icon: "🛫", defaultDuration: 0.5, supportedEffectOptions: ["from-left", "from-right", "from-top", "from-bottom", "from-top-left", "from-top-right", "from-bottom-left", "from-bottom-right"] },
    { id: "float-in", name: "Float In", category: "entrance", icon: "🎈", defaultDuration: 1.0, supportedEffectOptions: ["float-up", "float-down"] },
    { id: "split", name: "Split", category: "entrance", icon: "✂️", defaultDuration: 1.5, supportedEffectOptions: ["horizontal-in", "horizontal-out", "vertical-in", "vertical-out"] },
    { id: "wipe", name: "Wipe", category: "entrance", icon: "🧹", defaultDuration: 1.0, supportedEffectOptions: ["from-left", "from-right", "from-top", "from-bottom"] },
    { id: "shape", name: "Shape", category: "entrance", icon: "◯", defaultDuration: 1.5, supportedEffectOptions: ["circle", "box", "diamond", "plus"] },
    { id: "wheel", name: "Wheel", category: "entrance", icon: "🎡", defaultDuration: 2.0, supportedEffectOptions: ["1-spoke", "2-spoke", "3-spoke", "4-spoke", "8-spoke"] },
    { id: "random-bars", name: "Random Bars", category: "entrance", icon: "▤", defaultDuration: 1.0, supportedEffectOptions: ["horizontal", "vertical"] },
    { id: "grow-turn", name: "Grow & Turn", category: "entrance", icon: "🔄", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "zoom", name: "Zoom", category: "entrance", icon: "🔍", defaultDuration: 0.5, supportedEffectOptions: ["in", "out"] },
    { id: "swivel", name: "Swivel", category: "entrance", icon: "🌀", defaultDuration: 1.5, supportedEffectOptions: [] },
    { id: "bounce", name: "Bounce", category: "entrance", icon: "🦘", defaultDuration: 2.0, supportedEffectOptions: [] },
    // Additional Entrance Animations
    { id: "blinds", name: "Blinds", category: "entrance", icon: "▒", defaultDuration: 1.0, supportedEffectOptions: ["horizontal", "vertical"] },
    { id: "box", name: "Box", category: "entrance", icon: "⬜", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "checkerboard", name: "Checkerboard", category: "entrance", icon: "🏁", defaultDuration: 1.0, supportedEffectOptions: ["across", "down"] },
    { id: "circle", name: "Circle", category: "entrance", icon: "🔴", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "crawl-in", name: "Crawl In", category: "entrance", icon: "🐛", defaultDuration: 1.0, supportedEffectOptions: ["from-left", "from-right", "from-top", "from-bottom"] },
    { id: "diamond", name: "Diamond", category: "entrance", icon: "💎", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "dissolve-in", name: "Dissolve In", category: "entrance", icon: "🌫️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "expand", name: "Expand", category: "entrance", icon: "↔️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "flash-once", name: "Flash Once", category: "entrance", icon: "⚡", defaultDuration: 0.5, supportedEffectOptions: [] },
    { id: "peek-in", name: "Peek In", category: "entrance", icon: "👀", defaultDuration: 1.0, supportedEffectOptions: ["from-bottom", "from-left", "from-right", "from-top"] },
    { id: "plus", name: "Plus", category: "entrance", icon: "➕", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "random-effects", name: "Random Effects", category: "entrance", icon: "🔀", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "spiral-in", name: "Spiral In", category: "entrance", icon: "🌀", defaultDuration: 1.5, supportedEffectOptions: [] },
    { id: "stretch", name: "Stretch", category: "entrance", icon: "↕️", defaultDuration: 1.0, supportedEffectOptions: ["across", "down"] },
    { id: "strips", name: "Strips", category: "entrance", icon: "░", defaultDuration: 1.0, supportedEffectOptions: ["left-down", "left-up", "right-down", "right-up"] },
    { id: "swish", name: "Swish", category: "entrance", icon: "💫", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "unfold", name: "Unfold", category: "entrance", icon: "📖", defaultDuration: 1.0, supportedEffectOptions: [] }
  ],
  emphasis: [
    { id: "pulse", name: "Pulse", category: "emphasis", icon: "💓", defaultDuration: 0.5, supportedEffectOptions: [] },
    { id: "color-pulse", name: "Colour Pulse", category: "emphasis", icon: "🌈", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "teeter", name: "Teeter", category: "emphasis", icon: "⚖️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "spin", name: "Spin", category: "emphasis", icon: "🔄", defaultDuration: 2.0, supportedEffectOptions: ["clockwise", "counterclockwise"] },
    { id: "grow-shrink", name: "Grow/Shrink", category: "emphasis", icon: "🔍", defaultDuration: 1.5, supportedEffectOptions: ["grow", "shrink"] },
    { id: "desaturate", name: "Desaturate", category: "emphasis", icon: "🎨", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "darken", name: "Darken", category: "emphasis", icon: "🌒", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "lighten", name: "Lighten", category: "emphasis", icon: "🌖", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "transparency", name: "Transparency", category: "emphasis", icon: "👻", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "object-color", name: "Object Colour", category: "emphasis", icon: "🖌️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "complementary-color", name: "Complementary Colour", category: "emphasis", icon: "🎨", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "line-color", name: "Line Colour", category: "emphasis", icon: "✏️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "fill-color", name: "Fill Colour", category: "emphasis", icon: "🫗", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "brush-color", name: "Brush Colour", category: "emphasis", icon: "🖌️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "font-color", name: "Font Colour", category: "emphasis", icon: "🅰️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "underline", name: "Underline", category: "emphasis", icon: "U", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "bold-flash", name: "Bold Flash", category: "emphasis", icon: "B", defaultDuration: 0.5, supportedEffectOptions: [] },
    { id: "bold-reveal", name: "Bold Reveal", category: "emphasis", icon: "Bold", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "wave", name: "Wave", category: "emphasis", icon: "🌊", defaultDuration: 1.5, supportedEffectOptions: [] },
    // Additional Emphasis Animations
    { id: "blink", name: "Blink", category: "emphasis", icon: "💡", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "change-font", name: "Change Font", category: "emphasis", icon: "🔤", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "change-font-size", name: "Change Font Size", category: "emphasis", icon: "font-size", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "change-font-style", name: "Change Font Style", category: "emphasis", icon: "italic", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "contrasting-color", name: "Contrasting Colour", category: "emphasis", icon: "◐", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "flicker", name: "Flicker", category: "emphasis", icon: "⚡", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "grow-with-color", name: "Grow With Colour", category: "emphasis", icon: "📈", defaultDuration: 1.5, supportedEffectOptions: [] },
    { id: "shimmer", name: "Shimmer", category: "emphasis", icon: "✨", defaultDuration: 1.0, supportedEffectOptions: [] }
  ],
  exit: [
    { id: "disappear", name: "Disappear", category: "exit", icon: "❌", defaultDuration: 0.0, supportedEffectOptions: [] },
    { id: "fade-out", name: "Fade", category: "exit", icon: "🌫️", defaultDuration: 0.5, supportedEffectOptions: [] },
    { id: "fly-out", name: "Fly Out", category: "exit", icon: "🛫", defaultDuration: 0.5, supportedEffectOptions: ["to-left", "to-right", "to-top", "to-bottom", "to-top-left", "to-top-right", "to-bottom-left", "to-bottom-right"] },
    { id: "float-out", name: "Float Out", category: "exit", icon: "🎈", defaultDuration: 1.0, supportedEffectOptions: ["float-up", "float-down"] },
    { id: "split-out", name: "Split", category: "exit", icon: "✂️", defaultDuration: 1.5, supportedEffectOptions: ["horizontal-in", "horizontal-out", "vertical-in", "vertical-out"] },
    { id: "wipe-out", name: "Wipe", category: "exit", icon: "🧹", defaultDuration: 1.0, supportedEffectOptions: ["to-left", "to-right", "to-top", "to-bottom"] },
    { id: "shape-out", name: "Shape", category: "exit", icon: "◯", defaultDuration: 1.5, supportedEffectOptions: ["circle", "box", "diamond", "plus"] },
    { id: "wheel-out", name: "Wheel", category: "exit", icon: "🎡", defaultDuration: 2.0, supportedEffectOptions: ["1-spoke", "2-spoke", "3-spoke", "4-spoke", "8-spoke"] },
    { id: "random-bars-out", name: "Random Bars", category: "exit", icon: "▤", defaultDuration: 1.0, supportedEffectOptions: ["horizontal", "vertical"] },
    { id: "shrink-turn", name: "Shrink & Turn", category: "exit", icon: "🔄", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "zoom-out", name: "Zoom", category: "exit", icon: "🔍", defaultDuration: 0.5, supportedEffectOptions: ["in", "out"] },
    { id: "swivel-out", name: "Swivel", category: "exit", icon: "🌀", defaultDuration: 1.5, supportedEffectOptions: [] },
    { id: "bounce-out", name: "Bounce", category: "exit", icon: "🦘", defaultDuration: 2.0, supportedEffectOptions: [] },
    // Additional Exit Animations
    { id: "blinds-out", name: "Blinds", category: "exit", icon: "▒", defaultDuration: 1.0, supportedEffectOptions: ["horizontal", "vertical"] },
    { id: "box-out", name: "Box", category: "exit", icon: "⬜", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "checkerboard-out", name: "Checkerboard", category: "exit", icon: "🏁", defaultDuration: 1.0, supportedEffectOptions: ["across", "down"] },
    { id: "circle-out", name: "Circle", category: "exit", icon: "🔴", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "collapse", name: "Collapse", category: "exit", icon: "🗜️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "crawl-out", name: "Crawl Out", category: "exit", icon: "🐛", defaultDuration: 1.0, supportedEffectOptions: ["to-left", "to-right", "to-top", "to-bottom"] },
    { id: "diamond-out", name: "Diamond", category: "exit", icon: "💎", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "dissolve-out", name: "Dissolve Out", category: "exit", icon: "🌫️", defaultDuration: 1.0, supportedEffectOptions: [] },
    { id: "peek-out", name: "Peek Out", category: "exit", icon: "👀", defaultDuration: 1.0, supportedEffectOptions: ["to-bottom", "to-left", "to-right", "to-top"] },
    { id: "plus-out", name: "Plus", category: "exit", icon: "➕", defaultDuration: 1.0, supportedEffectOptions: ["in", "out"] },
    { id: "spiral-out", name: "Spiral Out", category: "exit", icon: "🌀", defaultDuration: 1.5, supportedEffectOptions: [] },
    { id: "stretchy", name: "Stretchy", category: "exit", icon: "↔️", defaultDuration: 1.0, supportedEffectOptions: ["across", "down"] },
    { id: "strips-out", name: "Strips", category: "exit", icon: "░", defaultDuration: 1.0, supportedEffectOptions: ["left-down", "left-up", "right-down", "right-up"] }
  ],
  motion_path: [
    { id: "line-left", name: "Line Left", category: "motion_path", icon: "⬅️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "line-right", name: "Line Right", category: "motion_path", icon: "➡️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "line-up", name: "Line Up", category: "motion_path", icon: "⬆️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "line-down", name: "Line Down", category: "motion_path", icon: "⬇️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "arc", name: "Arc", category: "motion_path", icon: "↩️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "turn", name: "Turn", category: "motion_path", icon: "↪️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-circle", name: "Circle Path", category: "motion_path", icon: "◯", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-square", name: "Square Path", category: "motion_path", icon: "⬜", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-triangle", name: "Triangle Path", category: "motion_path", icon: "🔺", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-diamond", name: "Diamond Path", category: "motion_path", icon: "🔶", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-trapezoid", name: "Trapezoid Path", category: "motion_path", icon: "⏢", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-hexagon", name: "Hexagon Path", category: "motion_path", icon: "⬡", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-octagon", name: "Octagon Path", category: "motion_path", icon: "⬢", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-heart", name: "Heart Path", category: "motion_path", icon: "❤️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-star", name: "Star Path", category: "motion_path", icon: "⭐", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-wave", name: "Wave Path", category: "motion_path", icon: "〰️", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-zigzag", name: "Zigzag Path", category: "motion_path", icon: "zigzag", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "path-spiral", name: "Spiral Path", category: "motion_path", icon: "🌀", defaultDuration: 2.5, supportedEffectOptions: ["reverse"] },
    { id: "bounce-left", name: "Bounce Left", category: "motion_path", icon: "bounce-left", defaultDuration: 2.0, supportedEffectOptions: [] },
    { id: "bounce-right", name: "Bounce Right", category: "motion_path", icon: "bounce-right", defaultDuration: 2.0, supportedEffectOptions: [] },
    { id: "curved-path", name: "Curved Path", category: "motion_path", icon: "curve", defaultDuration: 2.0, supportedEffectOptions: ["reverse"] },
    { id: "loop", name: "Loop Path", category: "motion_path", icon: "➰", defaultDuration: 2.0, supportedEffectOptions: [] },
    { id: "custom-path", name: "Custom Path", category: "motion_path", icon: "🖋️", defaultDuration: 2.0, supportedEffectOptions: [] }
  ]
};

export const getAnimationConfig = (id) => {
  const allAnimations = [
    ...animationEffects.entrance,
    ...animationEffects.emphasis,
    ...animationEffects.exit,
    ...animationEffects.motion_path
  ];
  return allAnimations.find(a => a.id === id) || null;
};
